services:
  web:
    build: .
    container_name: pipeline-analyzer-web
    ports:
      - "5000:5000"
    volumes:

      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - JENKINS_URL=http://172.17.0.1:8080
      - JENKINS_USER=manikandan791
      - JENKINS_TOKEN=mani12345678
      - GROQ_API_KEY=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

    command: >
      bash -c "poetry install && flask run --host=0.0.0.0 --port=5000"
